version: '3'
services:
  social-media-volume-db:
    container_name: social-media-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE= SocialMedia
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - social-media-volume-db:/var/lib/mysql

volumes:
  social-media-volume-db:

