#spring:
#  application:
#    name: social-media
#  profiles:
#    active: dev
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:8080
#    title: API Service
#    version: 1.0.0
#---
#server:
#  port: 8081
#spring:
#  config:
#    activate:
#      on-profile: test
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:${server.port}
#    title: API Service
#    version: 1.0.0
#---
#server:
#  port: 8082
#spring:
#  config:
#    activate:
#      on-profile: prod
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:${server.port}
#    title: API Service
#    version: 1.0.0